using System.ComponentModel;
using System.Net.Http.Json;
using System.Text.Json;
using ModelContextProtocol.Server;
using Shared;
using FluentValidation;

namespace McpServer;

using TriviaQuestions = List<TriviaItem<QuestionDto>>;
using Validator = IValidator<TriviaItem<QuestionDto>>;

[McpServerToolType]
public class ApiService(HttpClient client, JsonSerializerOptions jsonOptions)
{
    [McpServerTool, Description("Returns a list of trivia questions stored in a database in JSON format.")]
    public async Task<TriviaQuestions> GetQuestionsAsync()
    {
        var response = await client.GetAsync("http://localhost:5164/trivia");
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadFromJsonAsync<TriviaQuestions>(jsonOptions) ?? [];
    }

    [McpServerTool, Description("Adds one or more trivia questions to the database via a REST API.")]
    public async Task<string> AddQuestionsAsync(TriviaQuestions questions, Validator validator)
    {
        // validate the data first
        var results = questions.Select(validator.Validate).ToList();
        var failures = results
            .SelectMany((result, index) => result.Errors.Select(error => (Index: index, Error: error)))
            .ToList();

        if (failures.Count > 0)
        {
            return $"Validation failed with {failures.Count} errors:\n" +
                   string.Join("\n",
                       failures.Select(f => $"Item {f.Index}: {f.Error.PropertyName} - {f.Error.ErrorMessage}"));
        }

        var response = await client.PostAsJsonAsync("http://localhost:5164/trivia/batch", questions, jsonOptions);
        response.EnsureSuccessStatusCode();
        return $"{questions.Count} Questions added successfully.";
    }

    [McpServerTool,
     Description(
         "Updates a trivia question in the database via a REST API. The Id should be provided in the question object itself.")]
    public async Task<string> UpdateQuestionAsync(TriviaItem<QuestionDto> question, Validator validator)
    {
        var result = await validator.ValidateAsync(question);
        if (!result.IsValid)
        {
            return "Validation failed:\n" +
                   string.Join("\n",
                       result.Errors.Select(e => $"{e.PropertyName} - {e.ErrorMessage}"));
        }

        var response = await client.PutAsJsonAsync("http://localhost:5164/trivia", question, jsonOptions);
        response.EnsureSuccessStatusCode();
        return $"Question with ID {question.Id} updated successfully.";
    }

    [McpServerTool, Description("Deletes a trivia question from the database via a REST API using its unique Id.")]
    public async Task<string> DeleteQuestionAsync(string id)
    {
        var response = await client.DeleteAsync($"http://localhost:5164/trivia/{id}");
        return response.IsSuccessStatusCode
            ? $"Question with ID {id} deleted successfully."
            : $"Failed to delete question with ID {id}. It may not exist.";
    }


    // Note: the code for tool was generated by claude based on my suggestion to include a guide for any AI agent that needs to create trivia questions.
    // As the structure is not mirroring a "standard trivia question" format, having a detailed guide is important.
    // Additionally, should figure out if there's a better way to handle validation feedback to the llm than requiring it to ask for what the rules are.
    [McpServerTool]
    [Description("Get comprehensive guide on trivia question structure, validation rules, and best practices")]
    public static string GetTriviaQuestionGuide()
    {
        return JsonSerializer.Serialize(new
        {
            ConceptualOverview = new
            {
                Description = "Trivia items contain a main prompt with multiple related sub-questions",
                Structure = "One prompt groups related questions that share a theme",
                OtherFields = """
                              Tags and Difficulty are mandatory metadata.
                              Tags should go from general to specific (e.g., ["Sports", "Football", "Premier League"])
                              Difficulty levels: Easy, Medium, Hard indicate overall challenge.
                              Challenge level should correlate with two factors:
                              - How niche is the overall topic?
                              - How tricky are the questions themselves?
                              """,
                Philosophy = "Questions should test knowledge cohesively around a single topic"
            },

            ValidationRules = new
            {
                Rules = TriviaQuestionValidator.GetMinAndMaxGuide()
            },

            QuestionTypes = new
            {
                MultipleChoice = new
                {
                    Description = "Questions where users pick from predefined options",
                    AnswerField = "multipleChoiceAnswer",
                    RequiredFields = new[] { "correctAnswers" },
                    BestPractices = new[]
                    {
                        "Prompt should list the available choices",
                        "Use correctAnswers array to define valid options",
                        "Each question picks ONE answer from the choices"
                    },
                    GoodExample = new
                    {
                        prompt =
                            "Which programming language is each framework primarily used with: Python or JavaScript?",
                        questions = new[]
                        {
                            new { questionText = "Django", multipleChoiceAnswer = "Python" },
                            new { questionText = "React", multipleChoiceAnswer = "JavaScript" }
                        },
                        correctAnswers = new[] { "Python", "JavaScript" }
                    },
                    BadExample = new
                    {
                        prompt = "Programming questions", // Too vague
                        questions = new[]
                        {
                            new
                            {
                                questionText = "What is Django?", multipleChoiceAnswer = "Web framework"
                            } // Answer not in correctAnswers
                        },
                        correctAnswers = new[] { "Python", "JavaScript" }
                    }
                },

                TrueOrFalse = new
                {
                    Description = "Questions with boolean answers",
                    AnswerField = "trueOrFalseAnswer",
                    BestPractices = new[]
                    {
                        "Prompt should indicate it's a true/false format",
                        "Questions should be clear statements, not ambiguous",
                        "Mix of true and false answers for balance"
                    },
                    GoodExample = new
                    {
                        prompt = "Which of the following statements about the Solar System are true?",
                        questions = new[]
                        {
                            new { questionText = "The Sun is a star.", trueOrFalseAnswer = true },
                            new { questionText = "Jupiter is the smallest planet.", trueOrFalseAnswer = false }
                        }
                    },
                    BadExample = new
                    {
                        prompt = "Is the following true or false?", // Too vague
                        why = "The prompt doesn't specify a meaningful topic and questions are all over the place.",
                        questions = new[]
                        {
                            new { questionText = "The Earth is flat.", trueOrFalseAnswer = false },
                            new { questionText = "Football is played on ice.", trueOrFalseAnswer = false }
                        }
                    }
                },

                FillInTheBlank = new
                {
                    Description = "Questions requiring specific text answers",
                    AnswerField = "fillInTheBlankAnswer",
                    AnswerFormat = "Array of strings (multiple acceptable answers)",
                    BestPractices = new[]
                    {
                        "Prompt should indicate the matching/completion task",
                        "Provide multiple acceptable answers when possible",
                        "Keep answers short and specific",
                        "Consider synonyms and variations but don't force them"
                    },
                    GoodExample = new
                    {
                        prompt = "Match these programming concepts to their definitions:",
                        questions = new[]
                        {
                            new
                            {
                                questionText = "A function that calls itself",
                                fillInTheBlankAnswer = new[] { "Recursion", "Recursive function" }
                            },
                            new
                            {
                                questionText = "Data hiding in objects",
                                fillInTheBlankAnswer = new[] { "Encapsulation" }
                            }
                        }
                    },
                    BadExample = new
                    {
                        prompt = "Fill in the blanks:", // Too vague
                        why = "The prompt doesn't specify what topic or type of answers are expected.",
                        questions = new[]
                        {
                            new
                            {
                                questionText = "The capital of France is ____.",
                                fillInTheBlankAnswer = new[] { "Paris" }
                            },
                            new
                            {
                                questionText = "Water boils at ____ degrees Celsius.",
                                fillInTheBlankAnswer = new[] { "100", "one hundred" }
                            }
                        }
                    }
                },

                Ordering = new
                {
                    Description = "Questions requiring sequential arrangement",
                    AnswerField = "orderingAnswer",
                    AnswerFormat = "Integer representing position in sequence",
                    BestPractices = new[]
                    {
                        "Prompt should clearly indicate ordering criteria",
                        "Use consecutive integers starting from 1 all the way to N where N stands for number of questions",
                        "Ensure clear chronological/logical sequence exists",
                        "Prefer larger sets (4+ items) for meaningful ordering"
                    },
                    GoodExample = new
                    {
                        prompt = "Order these programming languages by year of first release (earliest to latest):",
                        questions = new[]
                        {
                            new { questionText = "Fortran", orderingAnswer = 1 },
                            new { questionText = "C", orderingAnswer = 2 },
                            new { questionText = "Python", orderingAnswer = 3 }
                        }
                    },
                    BadExample = new
                    {
                        prompt = "Arrange these random items:", // Too vague
                        why =
                            "The prompt doesn't specify a clear ordering criterion. and the answers are non-consecutive.",
                        questions = new[]
                        {
                            new { questionText = "Apple", orderingAnswer = 3 },
                            new { questionText = "Banana", orderingAnswer = 1 }
                        }
                    }
                }
            },

            CommonMistakes = new[]
            {
                "Mixing question types within one trivia item",
                "Prompts that don't clearly explain the task",
                "Unrelated questions grouped together",
                "Missing or incorrect correctAnswers for MultipleChoice",
                "Answers exceeding character limits",
                "Non-consecutive ordering numbers",
                "Ambiguous true/false statements",
                "Too few or too many questions per item"
            },

            QualityGuidelines = new
            {
                TopicCoherence = "All questions should relate to the prompt theme",
                DifficultyBalance = "Mix easy and challenging questions within reasonable bounds",
                ClearInstructions = "Prompt should make the task obvious to users",
                AccurateAnswers = "Verify all answers are factually correct",
                ConsistentFormat = "Follow the structure patterns shown in examples"
            }
        });
    }
}
