--
-- PostgreSQL database dump
--

\restrict OvdbYjwOEgG9phexjz7BxfgIKBdhlphcfTms581fcA4aEwiij6FYu0ahhfSysfU

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: triviaitems; Type: TABLE DATA; Schema: public; Owner: devuser
--

INSERT INTO public.triviaitems (data, createdat) VALUES
	('{"Id": "193ca678-c2ed-4d1b-967c-29538b09c207", "Tags": ["History", "Chronology"], "Prompt": "Order these historical events from earliest to latest:", "Content": {"Questions": [{"QuestionText": "American Declaration of Independence", "OrderingAnswer": 1}, {"QuestionText": "French Revolution", "OrderingAnswer": 2}, {"QuestionText": "Industrial Revolution begins", "OrderingAnswer": 3}, {"QuestionText": "World War I begins", "OrderingAnswer": 4}, {"QuestionText": "World War II begins", "OrderingAnswer": 5}, {"QuestionText": "Moon Landing", "OrderingAnswer": 6}, {"QuestionText": "Fall of the Berlin Wall", "OrderingAnswer": 7}, {"QuestionText": "Human genome project completed", "OrderingAnswer": 8}]}, "Difficulty": 1, "QuestionType": 3}', '2026-01-05 01:51:06.557861+00'),
	('{"Id": "748efff2-da48-44d9-b8f4-078dc4d09c3b", "Tags": ["Science", "Astronomy", "Solar System", "Moons"], "Prompt": "Which of the following statements about rare moons in the Solar System are true?", "Content": {"Questions": [{"QuestionText": "Mimas is a moon of Saturn.", "TrueOrFalseAnswer": true}, {"QuestionText": "Io is known for its active volcanoes.", "TrueOrFalseAnswer": true}, {"QuestionText": "Triton orbits Jupiter.", "TrueOrFalseAnswer": false}, {"QuestionText": "Phobos is a moon of Mars.", "TrueOrFalseAnswer": true}, {"QuestionText": "Europa is smaller than Mercury.", "TrueOrFalseAnswer": false}, {"QuestionText": "Titan is the largest moon of Saturn.", "TrueOrFalseAnswer": true}, {"QuestionText": "Callisto orbits Neptune.", "TrueOrFalseAnswer": false}, {"QuestionText": "Ganymede is the largest moon in the Solar System.", "TrueOrFalseAnswer": true}]}, "Difficulty": 2, "QuestionType": 1}', '2026-01-05 01:51:06.561874+00'),
	('{"Id": "500b5869-ff89-4fd5-9c52-a24680902bd1", "Tags": ["Awards", "Nobel Prize", "Laureates"], "Prompt": "Match these Nobel Prize winners to their field:", "Content": {"Questions": [{"QuestionText": "Albert Einstein", "FillInTheBlankAnswer": ["Physics"]}, {"QuestionText": "Marie Curie", "FillInTheBlankAnswer": ["Chemistry"]}, {"QuestionText": "Martin Luther King Jr.", "FillInTheBlankAnswer": ["Peace"]}, {"QuestionText": "Erwin Schrödinger", "FillInTheBlankAnswer": ["Physics"]}, {"QuestionText": "Alfred Nobel", "FillInTheBlankAnswer": ["Chemistry"]}, {"QuestionText": "Malala Yousafzai", "FillInTheBlankAnswer": ["Peace"]}, {"QuestionText": "Niels Bohr", "FillInTheBlankAnswer": ["Physics"]}, {"QuestionText": "Linus Pauling", "FillInTheBlankAnswer": ["Chemistry"]}]}, "Difficulty": 1, "QuestionType": 2}', '2026-01-05 01:51:06.562185+00'),
	('{"Id": "d3c9ca67-24d5-4e11-ba6c-3185443a1748", "Tags": ["Sports", "Athletes", "Sport Identification"], "Prompt": "Which sport does the following athlete play: Football, Basketball, or Tennis?", "Content": {"Questions": [{"QuestionText": "Lionel Messi", "MultipleChoiceAnswer": "Football"}, {"QuestionText": "LeBron James", "MultipleChoiceAnswer": "Basketball"}, {"QuestionText": "Roger Federer", "MultipleChoiceAnswer": "Tennis"}, {"QuestionText": "Cristiano Ronaldo", "MultipleChoiceAnswer": "Football"}, {"QuestionText": "Rafael Nadal", "MultipleChoiceAnswer": "Tennis"}, {"QuestionText": "Stephen Curry", "MultipleChoiceAnswer": "Basketball"}, {"QuestionText": "Neymar Jr.", "MultipleChoiceAnswer": "Football"}, {"QuestionText": "Serena Williams", "MultipleChoiceAnswer": "Tennis"}], "CorrectAnswers": ["Football", "Basketball", "Tennis"]}, "Difficulty": 1, "QuestionType": 0}', '2026-01-05 01:51:06.562448+00'),
	('{"Id": "ab180709-7b3d-46f1-9039-ac2a4a5ac950", "Tags": ["Awards", "Nobel Prize", "History"], "Prompt": "Order these Nobel Prizes based on their year of first award:", "Content": {"Questions": [{"QuestionText": "Peace", "OrderingAnswer": 1}, {"QuestionText": "Physics", "OrderingAnswer": 2}, {"QuestionText": "Chemistry", "OrderingAnswer": 3}, {"QuestionText": "Medicine", "OrderingAnswer": 4}, {"QuestionText": "Literature", "OrderingAnswer": 5}, {"QuestionText": "Economic Sciences", "OrderingAnswer": 6}]}, "Difficulty": 1, "QuestionType": 3}', '2026-01-05 01:51:06.56272+00'),
	('{"Id": "7d6edcb1-b85b-4e4c-b748-5ad95555f5a0", "Tags": ["Science", "Astronomy", "Solar System"], "Prompt": "Which of the following statements about the Solar System are true?", "Content": {"Questions": [{"QuestionText": "The Sun is a star.", "TrueOrFalseAnswer": true}, {"QuestionText": "Jupiter is the smallest planet.", "TrueOrFalseAnswer": false}, {"QuestionText": "Saturn has rings.", "TrueOrFalseAnswer": true}, {"QuestionText": "Mercury has more moons than Earth.", "TrueOrFalseAnswer": false}, {"QuestionText": "Venus rotates clockwise.", "TrueOrFalseAnswer": true}, {"QuestionText": "Pluto is still classified as a planet.", "TrueOrFalseAnswer": false}, {"QuestionText": "Mars is known as the Red Planet.", "TrueOrFalseAnswer": true}, {"QuestionText": "Neptune is farther from the Sun than Uranus.", "TrueOrFalseAnswer": true}]}, "Difficulty": 1, "QuestionType": 1}', '2026-01-05 01:51:06.563197+00'),
	('{"Id": "d072de45-43a1-482c-a879-229d398105ff", "Tags": ["Technology", "Inventions", "Chronology"], "Prompt": "Order these technological inventions from earliest to latest:", "Content": {"Questions": [{"QuestionText": "Printing press", "OrderingAnswer": 1}, {"QuestionText": "Steam engine", "OrderingAnswer": 2}, {"QuestionText": "Telephone", "OrderingAnswer": 3}, {"QuestionText": "Light bulb", "OrderingAnswer": 4}, {"QuestionText": "Radio", "OrderingAnswer": 5}, {"QuestionText": "Television", "OrderingAnswer": 6}, {"QuestionText": "Personal computer", "OrderingAnswer": 7}, {"QuestionText": "Internet", "OrderingAnswer": 8}]}, "Difficulty": 1, "QuestionType": 3}', '2026-01-05 01:51:06.563724+00'),
	('{"Id": "0d03d02a-897d-4796-85fe-837473d759e7", "Tags": ["Music", "Classical Music", "Composers"], "Prompt": "Which of the following composers created these pieces: Mozart, Beethoven, or Chopin?", "Content": {"Questions": [{"QuestionText": "Symphony No. 40", "MultipleChoiceAnswer": "Mozart"}, {"QuestionText": "Fur Elise", "MultipleChoiceAnswer": "Beethoven"}, {"QuestionText": "Nocturne in E-flat Major", "MultipleChoiceAnswer": "Chopin"}, {"QuestionText": "Piano Sonata No. 14", "MultipleChoiceAnswer": "Beethoven"}, {"QuestionText": "The Magic Flute", "MultipleChoiceAnswer": "Mozart"}, {"QuestionText": "Ballade No. 1", "MultipleChoiceAnswer": "Chopin"}, {"QuestionText": "Requiem", "MultipleChoiceAnswer": "Mozart"}, {"QuestionText": "Moonlight Sonata", "MultipleChoiceAnswer": "Beethoven"}], "CorrectAnswers": ["Mozart", "Beethoven", "Chopin"]}, "Difficulty": 1, "QuestionType": 0}', '2026-01-05 01:51:06.563971+00'),
	('{"Id": "2e52359f-5542-4d55-bc87-be15e2fe1e10", "Tags": ["Technology", "Programming", "Programming Languages", "History"], "Prompt": "Order these programming languages by year of first release (earliest to latest):", "Content": {"Questions": [{"QuestionText": "Fortran", "OrderingAnswer": 1}, {"QuestionText": "Lisp", "OrderingAnswer": 2}, {"QuestionText": "C", "OrderingAnswer": 3}, {"QuestionText": "Python", "OrderingAnswer": 4}, {"QuestionText": "Java", "OrderingAnswer": 5}, {"QuestionText": "JavaScript", "OrderingAnswer": 6}, {"QuestionText": "C#", "OrderingAnswer": 7}, {"QuestionText": "Go", "OrderingAnswer": 8}]}, "Difficulty": 2, "QuestionType": 3}', '2026-01-05 01:58:43.823185+00'),
	('{"Id": "f503e198-00fc-4bfe-ac39-89e828ba0d68", "Tags": ["Sports", "Football", "FIFA World Cup", "History"], "Prompt": "Order these countries by year of their first FIFA World Cup win (earliest → latest).", "Content": {"Questions": [{"Explanation": "First win: 1930", "QuestionText": "Uruguay", "OrderingAnswer": 1}, {"Explanation": "First win: 1934", "QuestionText": "Italy", "OrderingAnswer": 2}, {"Explanation": "First win: 1958", "QuestionText": "Brazil", "OrderingAnswer": 3}, {"Explanation": "First win: 1966", "QuestionText": "England", "OrderingAnswer": 4}, {"Explanation": "First win: 1978", "QuestionText": "Argentina", "OrderingAnswer": 5}]}, "Difficulty": 2, "QuestionType": 3}', '2026-01-07 01:58:36.235868+00'),
	('{"Id": "2da7c29e-fa66-4502-b82f-05857ea20e91", "Tags": ["Sports", "Football", "National Teams"], "Prompt": "Which nation does this footballer represent?", "Content": {"Questions": [{"QuestionText": "Wilfried Zaha", "FillInTheBlankAnswer": ["Ivory Coast"]}, {"QuestionText": "Sergej Milinković-Savić", "FillInTheBlankAnswer": ["Serbia"]}, {"QuestionText": "Hakim Ziyech", "FillInTheBlankAnswer": ["Morocco"]}, {"QuestionText": "Josip Iličić", "FillInTheBlankAnswer": ["Slovenia"]}, {"QuestionText": "Takumi Minamino", "FillInTheBlankAnswer": ["Japan"]}, {"QuestionText": "Andrej Kramarić", "FillInTheBlankAnswer": ["Croatia"]}, {"QuestionText": "Quincy Promes", "FillInTheBlankAnswer": ["Netherlands"]}, {"QuestionText": "Matheus Cunha", "FillInTheBlankAnswer": ["Brazil"]}]}, "Difficulty": 1, "QuestionType": 2}', '2026-01-07 02:05:16.825575+00'),
	('{"Id": "5085bc98-8f69-4209-81f1-18cc502c9824", "Tags": ["Sports", "Tennis", "National Teams"], "Prompt": "Which nation does this tennis player represent?", "Content": {"Questions": [{"QuestionText": "Alex de Minaur", "FillInTheBlankAnswer": ["Australia"]}, {"QuestionText": "Hubert Hurkacz", "FillInTheBlankAnswer": ["Poland"]}, {"QuestionText": "Dusan Lajovic", "FillInTheBlankAnswer": ["Serbia"]}, {"QuestionText": "Karen Khachanov", "FillInTheBlankAnswer": ["Russia"]}, {"QuestionText": "Pablo Carreño Busta", "FillInTheBlankAnswer": ["Spain"]}, {"QuestionText": "Borna Ćorić", "FillInTheBlankAnswer": ["Croatia"]}, {"QuestionText": "Frances Tiafoe", "FillInTheBlankAnswer": ["USA"]}, {"QuestionText": "Yoshihito Nishioka", "FillInTheBlankAnswer": ["Japan"]}]}, "Difficulty": 1, "QuestionType": 2}', '2026-01-07 02:06:46.067456+00'),
	('{"Id": "ecd04ec8-db3c-4fa3-8a76-dcc69d2d369a", "Tags": ["Sports", "Ice Hockey", "National Teams"], "Prompt": "Which nation does this ice hockey player represent?", "Content": {"Questions": [{"QuestionText": "Mikko Rantanen", "FillInTheBlankAnswer": ["Finland"]}, {"QuestionText": "Roman Josi", "FillInTheBlankAnswer": ["Switzerland"]}, {"QuestionText": "Elias Pettersson", "FillInTheBlankAnswer": ["Sweden"]}, {"QuestionText": "David Pastrňák", "FillInTheBlankAnswer": ["Czech Republic"]}, {"QuestionText": "Leon Draisaitl", "FillInTheBlankAnswer": ["Germany"]}, {"QuestionText": "Mats Zuccarello", "FillInTheBlankAnswer": ["Norway"]}, {"QuestionText": "Mark Stone", "FillInTheBlankAnswer": ["Canada"]}, {"QuestionText": "Kevin Fiala", "FillInTheBlankAnswer": ["Switzerland"]}]}, "Difficulty": 1, "QuestionType": 2}', '2026-01-07 02:06:46.069578+00'),
	('{"Id": "ce2f108b-7d17-4ed8-bfd0-f2de09dcd8d3", "Tags": ["Sports", "Basketball", "National Teams"], "Prompt": "Which nation does this basketball player represent?", "Content": {"Questions": [{"QuestionText": "Bojan Bogdanović", "FillInTheBlankAnswer": ["Croatia"]}, {"QuestionText": "Patty Mills", "FillInTheBlankAnswer": ["Australia"]}, {"QuestionText": "Tomas Satoransky", "FillInTheBlankAnswer": ["Czech Republic"]}, {"QuestionText": "Dennis Schröder", "FillInTheBlankAnswer": ["Germany"]}, {"QuestionText": "Facundo Campazzo", "FillInTheBlankAnswer": ["Argentina"]}, {"QuestionText": "Rudy Gobert", "FillInTheBlankAnswer": ["France"]}, {"QuestionText": "Raul Neto", "FillInTheBlankAnswer": ["Brazil"]}, {"QuestionText": "Sviatoslav Mykhailiuk", "FillInTheBlankAnswer": ["Ukraine"]}]}, "Difficulty": 1, "QuestionType": 2}', '2026-01-07 02:06:46.069901+00'),
	('{"Id": "c91c4d4c-5573-4296-8c98-f62b78d54033", "Tags": ["Entertainment", "Film", "Actors"], "Prompt": "Which actor stars in each of these movies? Choose from: Emily Blunt, Oscar Isaac, Adam Driver.", "Content": {"Questions": [{"QuestionText": "Edge of Tomorrow", "MultipleChoiceAnswer": "Emily Blunt"}, {"QuestionText": "Ex Machina", "MultipleChoiceAnswer": "Oscar Isaac"}, {"QuestionText": "Marriage Story", "MultipleChoiceAnswer": "Adam Driver"}, {"QuestionText": "A Quiet Place", "MultipleChoiceAnswer": "Emily Blunt"}, {"QuestionText": "Inside Llewyn Davis", "MultipleChoiceAnswer": "Oscar Isaac"}, {"QuestionText": "Paterson", "MultipleChoiceAnswer": "Adam Driver"}], "CorrectAnswers": ["Emily Blunt", "Oscar Isaac", "Adam Driver"]}, "Difficulty": 1, "QuestionType": 0}', '2026-01-07 02:08:45.254342+00'),
	('{"Id": "ff0d36c6-bcea-430f-b1e5-63111c58c1f2", "Tags": ["Entertainment", "Film", "Actors"], "Prompt": "Which actor stars in each of these movies? Choose from: Tom Hanks, Leonardo DiCaprio, Brad Pitt.", "Content": {"Questions": [{"QuestionText": "Forrest Gump", "MultipleChoiceAnswer": "Tom Hanks"}, {"QuestionText": "Titanic", "MultipleChoiceAnswer": "Leonardo DiCaprio"}, {"QuestionText": "Fight Club", "MultipleChoiceAnswer": "Brad Pitt"}, {"QuestionText": "Saving Private Ryan", "MultipleChoiceAnswer": "Tom Hanks"}, {"QuestionText": "Inception", "MultipleChoiceAnswer": "Leonardo DiCaprio"}, {"QuestionText": "Ocean''s Eleven", "MultipleChoiceAnswer": "Brad Pitt"}], "CorrectAnswers": ["Tom Hanks", "Leonardo DiCaprio", "Brad Pitt"]}, "Difficulty": 1, "QuestionType": 0}', '2026-01-07 02:09:27.10839+00'),
	('{"Id": "a9cb56a4-50b6-46cd-87fc-97746596e1ab", "Tags": ["Sports", "Football", "Premier League", "Manchester United"], "Prompt": "Order these Manchester United captains from earliest to latest.", "Content": {"Questions": [{"QuestionText": "Bryan Robson", "OrderingAnswer": 1}, {"QuestionText": "Steve Bruce", "OrderingAnswer": 2}, {"QuestionText": "Eric Cantona", "OrderingAnswer": 3}, {"QuestionText": "Roy Keane", "OrderingAnswer": 4}, {"QuestionText": "Gary Neville", "OrderingAnswer": 5}, {"QuestionText": "Nemanja Vidić", "OrderingAnswer": 6}, {"QuestionText": "Wayne Rooney", "OrderingAnswer": 7}, {"QuestionText": "Michael Carrick", "OrderingAnswer": 8}, {"QuestionText": "Antonio Valencia", "OrderingAnswer": 9}, {"QuestionText": "Ashley Young", "OrderingAnswer": 10}]}, "Difficulty": 2, "QuestionType": 3}', '2026-01-07 02:19:05.153113+00'),
	('{"Id": "12c42471-f2bb-4789-84a4-78cc390bfcf0", "Tags": ["Sports", "Football", "Premier League", "Liverpool"], "Prompt": "Order these Liverpool FC captains from earliest to latest.", "Content": {"Questions": [{"QuestionText": "Phil Thompson", "OrderingAnswer": 1}, {"QuestionText": "Graeme Souness", "OrderingAnswer": 2}, {"QuestionText": "Alan Hansen", "OrderingAnswer": 3}, {"QuestionText": "Steve McMahon", "OrderingAnswer": 4}, {"QuestionText": "Ian Rush", "OrderingAnswer": 5}, {"QuestionText": "John Barnes", "OrderingAnswer": 6}, {"QuestionText": "Jamie Redknapp", "OrderingAnswer": 7}, {"QuestionText": "Sami Hyypiä", "OrderingAnswer": 8}, {"QuestionText": "Steven Gerrard", "OrderingAnswer": 9}, {"QuestionText": "Jordan Henderson", "OrderingAnswer": 10}]}, "Difficulty": 2, "QuestionType": 3}', '2026-01-07 02:22:05.200732+00'),
	('{"Id": "803883de-6bbc-4d23-b6a7-edaaf0f87244", "Tags": ["Sports", "Football", "Career Statistics", "Goals"], "Prompt": "Order these footballers by total career goals, from most to least.", "Content": {"Questions": [{"Explanation": "Career total: 989+ goals", "QuestionText": "Erwin Helmchen", "OrderingAnswer": 1}, {"Explanation": "Career total: 956 goals", "QuestionText": "Cristiano Ronaldo", "OrderingAnswer": 2}, {"Explanation": "Career total: 950+ goals", "QuestionText": "Josef Bican", "OrderingAnswer": 3}, {"Explanation": "Career total: 934+ goals", "QuestionText": "Ronnie Rooke", "OrderingAnswer": 4}, {"Explanation": "Career total: 901 goals", "QuestionText": "Lionel Messi", "OrderingAnswer": 5}, {"Explanation": "Career total: 840+ goals", "QuestionText": "Jimmy Jones", "OrderingAnswer": 6}, {"Explanation": "Career total: 802 goals", "QuestionText": "Ferenc Puskás", "OrderingAnswer": 7}, {"Explanation": "Career total: 795+ goals", "QuestionText": "Ferenc Deák", "OrderingAnswer": 8}, {"Explanation": "Career total: 790+ goals", "QuestionText": "Abe Lenstra", "OrderingAnswer": 9}, {"Explanation": "Career total: 785 goals", "QuestionText": "Romário", "OrderingAnswer": 10}]}, "Difficulty": 2, "QuestionType": 3}', '2026-01-07 02:26:36.652997+00') ON CONFLICT DO NOTHING;


--
-- PostgreSQL database dump complete
--

\unrestrict OvdbYjwOEgG9phexjz7BxfgIKBdhlphcfTms581fcA4aEwiij6FYu0ahhfSysfU

